version: "3.8"

services:
  link_shortener:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STORAGE_TYPE=${STORAGE_TYPE}
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=link_shortener
      - POSTGRES_PASSWORD=h3tGFWqJRNEaTyycMITs3
      - POSTGRES_DB=link_shortener
    volumes:
      - ./data/inmemory:/app/data/inmemory
    ports:
      - "8080:8080"
    restart: unless-stopped
    stop_grace_period: 20s
    stop_signal: SIGINT
#    TODO: add healthcheck
#    healthcheck:
#      test: ["CMD", "curl", "http://localhost:8080/health"]

  postgres:
    image: postgres:14.3
    profiles:
      - postgres
    environment:
      - POSTGRES_USER=link_shortener
      - POSTGRES_PASSWORD=h3tGFWqJRNEaTyycMITs3
      - POSTGRES_DB=link_shortener
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
